# Windows CI build via the Appveyor service

version: '{build}'

# branches to build
branches:
  only:
    - master

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

environment:
  matrix:

    # constexpr not allowed for constructors that don't initialise
    # See: https://github.com/AcademySoftwareFoundation/Imath/pull/95
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   COMPILER: "Visual Studio 14 2015 Win64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: "Visual Studio 15 2017 Win64"

    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   COMPILER: "Visual Studio 16 2019"

# build platform, i.e. x86, x64, Any CPU.
platform:
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - echo --------------------------------------------------------------------------------
  - echo Appveyor environment info:
  - echo COMPILER = %COMPILER%, CONFIGURATION = %CONFIGURATION%
  - cmake -h
  - rem --------------------------------------------------------------------------------
  - rem Build third party dependencies:
  - mkdir build_external
  - cd build_external
  # TODO: Disable warnings with /W0, since both external libs are rotten with
  # warnings on Visual Studio?
  - cmake -G "%COMPILER%" ..\thirdparty\external
  - cmake --build . --config %CONFIGURATION%
  - cd ..

build_script:
  - echo --------------------------------------------------------------------------------
  - echo Build displaz:
  - mkdir build
  - cd build
  - cmake -G "%COMPILER%" -D DISPLAZ_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% ..
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target package
  # Hack: copy artifacts to avoid extra directories in deploy :(
  # See http://help.appveyor.com/discussions/questions/1244-path-inside-artifact-name-is-there-a-way-to-remove-it
  - cp displaz-*.exe ..
  - mkdir ..\latest
  - cp displaz-*.exe ..\latest\displaz-win64.exe

test_script:
  - ctest --timeout 100 -C %CONFIGURATION%

artifacts:
  - path: displaz-*.exe
    name: displaz-installer
  - path: latest\*.exe
    name: displaz-installer-latest


deploy:
  # Deploy CI builds of master to s3://displaz-data/builds/
  - provider: S3
    region: ap-southeast-2
    on:
      # Only deploy CI builds from master
      branch: master
    access_key_id:
      secure: y4QWdKCrKxq9JIQGjN87Gd/Pg4Vdmz+GaqoPlKxUuAY=
    secret_access_key:
      secure: uKUdBw0IvkIlc6sWpk/rwIQv1MmsexLLElD/Ir6bcXXetJUM0KoS5nQCaxSjQuV7
    bucket: displaz-data
    folder: builds/ci/
    set_public: true

